### ISSUE TITLE
Websocket doesn't play nice when running inside chromeOS's linux

### ISSUE THREAD

**Issue by gkrnours** [bjornbytes/lovr-webvr-server#2]
ChromeOS ship with a linux inside some kind of container. A server running on inside is not accessible from chrome which is outside the container. A solution is to access the server using either `penguin.linux.test` as domain or the ip of the container.

Using the domain name seems to break the auto-reload feature. I assume the container IP would also break the feature as there is a websocket listening to localhost:8081

**Comment by gkrnours** [comment]
I'll investigate and probably offer a PR as soon as I have some time. Which is after a night of sleep and probably a day of dayjob.

**Comment by bjornbytes** [comment]
Fixed by #3
